# Generated by Django 3.1.7 on 2021-04-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Srecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=200)),
                ('Fname', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Clas', models.CharField(max_length=10)),
                ('Rollno', models.CharField(max_length=10)),
            ],
        ),
    ]
